name: HSF CMS Analysis Test

on:
  pull_request:
  push:
    branches: 
     - master
  schedule:
     - cron: '0 0 1 * *'


jobs:
  test-analysis:
    runs-on: ubuntu-latest
    container: rootproject/root:6.26.10-conda

    permissions:
      contents: read
      packages: write

    name: run-test
    steps:

      - name: checkout folder
        uses: actions/checkout@v4

      - name: skim
        run: |
          mkdir -p $HOME/awesome-workshop/skims
          bash skim.sh root://eospublic.cern.ch//eos/root-eos/HiggsTauTauReduced/ $HOME/awesome-workshop/skims

      - name: histogram
        run: |
          mkdir -p $HOME/awesome-workshop/histograms
          bash histograms.sh $HOME/awesome-workshop/skims $HOME/awesome-workshop/histograms

      - name: plots
        run: |
          mkdir -p $HOME/awesome-workshop/plots
          bash plot.sh $HOME/awesome-workshop/histograms/histograms.root $HOME/awesome-workshop/plots

      - name: fit
        run: |
          mkdir -p $HOME/awesome-workshop/fit
          bash fit.sh $HOME/awesome-workshop/histograms/histograms.root $HOME/awesome-workshop/fit    
